version: '3'



services:
  mysql:
    image:
      mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./src/database-service/init:/docker-entrypoint-initdb.d
      - ./src/database-service/database-volume:/var/lib/mysql
    restart:
      always
    environment:
      - MYSQL_DATABASE=node
      - MYSQL_ROOT_PASSWORD=password 
      - MYSQL_USER=node 
      - MYSQL_PASSWORD=password
      - MYSQL_HOST=localhost
    ports:
      - 3306:3306
    # #for development
    # stdin_open: true # docker run -i
    # tty: true

