version: '3'



    # Nov.8 2020 | current problem
    
    # this is past me, I'm here to say that the current problem
    # you were facing was regarding connecting to the mysql database
    #error originate from the 
    #it's probably an error with my docker-compose.yml or Dockerfile 


services:
  database:
    image:
      mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./src/database-service/init:/docker-entrypoint-initdb.d
      - ./src/database-service/database-volume:/var/lib/mysql
    restart:
      always
    environment:
      - MYSQL_DATABASE=node
      - MYSQL_ROOT_PASSWORD=password 
      - MYSQL_USER=node 
      - MYSQL_PASSWORD=password
      - MYSQL_HOST=localhost
    ports:
      - 3306:3306
    expose:
      - 3306

    # #for development
    # stdin_open: true # docker run -i
    # tty: true
  server:
    build:
      context: ./src/node-service/
      dockerfile: Dockerfile
    container_name: node-server
    restart: unless-stopped
    ports:
      - "80:80"
      - "3306:3306"
    
      
